# Generated by Django 3.0.3 on 2020-03-01 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmsCreditsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_credits_uuid', models.UUIDField(default=uuid.uuid4)),
                ('sms_route_id', models.TextField()),
                ('sms_route', models.TextField()),
                ('sms_balance', models.TextField()),
            ],
        ),
    ]
