# Generated by Django 3.0.3 on 2020-03-01 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.TextField(default='ram@gmail.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
