# Generated by Django 3.0.3 on 2020-03-01 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReportsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_report_uuid', models.UUIDField(default=uuid.uuid4)),
                ('message_receipt_phone_number', models.TextField()),
                ('message_delivery_report', models.TextField()),
                ('message_report_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_uuid', models.UUIDField(default=uuid.uuid4)),
                ('reports', models.URLField()),
            ],
        ),
    ]
